package interfazCine;
import java.awt.CardLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author camac
 */
public class VtnConsultaPeliculas extends javax.swing.JFrame
{

    /**
     * Creates new form VtnConsultaPeliculas
     */
    public VtnConsultaPeliculas()
    {
        initComponents();
PPelicula.setLayout(new CardLayout());
    cl = (CardLayout) PPelicula.getLayout();
        PPelicula.setLayout(cl);
        JPanel pelicula1 = new JPanel();
pelicula1.setBackground(new java.awt.Color(153, 204, 255));
pelicula1.add(new JLabel(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_cinetec1-removebg-preview.png"))));
pelicula1.add(new JLabel("Misión Imposible: La sentencia final"));
PPelicula.add(pelicula1, "Pelicula 1");

JPanel pelicula2 = new JPanel();
pelicula2.setBackground(new java.awt.Color(153, 204, 255));
pelicula2.add(new JLabel(new javax.swing.ImageIcon(getClass().getResource("/imagenes/toystory.png"))));
pelicula2.add(new JLabel("Toy Story 4"));
PPelicula.add(pelicula2, "Pelicula 2");




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bg = new javax.swing.JPanel();
        PSup = new javax.swing.JPanel();
        PInf = new javax.swing.JPanel();
        PPelicula = new javax.swing.JPanel();
        PnlSig = new javax.swing.JPanel();
        LblFlecha = new javax.swing.JLabel();
        PnlAnt = new javax.swing.JPanel();
        lblAnt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PSup.setBackground(new java.awt.Color(83, 121, 164));

        javax.swing.GroupLayout PSupLayout = new javax.swing.GroupLayout(PSup);
        PSup.setLayout(PSupLayout);
        PSupLayout.setHorizontalGroup(
            PSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        PSupLayout.setVerticalGroup(
            PSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        bg.add(PSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        PInf.setBackground(new java.awt.Color(136, 167, 208));

        javax.swing.GroupLayout PPeliculaLayout = new javax.swing.GroupLayout(PPelicula);
        PPelicula.setLayout(PPeliculaLayout);
        PPeliculaLayout.setHorizontalGroup(
            PPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        PPeliculaLayout.setVerticalGroup(
            PPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        PnlSig.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                PnlSigMouseClicked(evt);
            }
        });

        LblFlecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFlecha.setText(">");

        javax.swing.GroupLayout PnlSigLayout = new javax.swing.GroupLayout(PnlSig);
        PnlSig.setLayout(PnlSigLayout);
        PnlSigLayout.setHorizontalGroup(
            PnlSigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblFlecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        PnlSigLayout.setVerticalGroup(
            PnlSigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblFlecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        lblAnt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnt.setText("<");

        javax.swing.GroupLayout PnlAntLayout = new javax.swing.GroupLayout(PnlAnt);
        PnlAnt.setLayout(PnlAntLayout);
        PnlAntLayout.setHorizontalGroup(
            PnlAntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAntLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblAnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        PnlAntLayout.setVerticalGroup(
            PnlAntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAntLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PInfLayout = new javax.swing.GroupLayout(PInf);
        PInf.setLayout(PInfLayout);
        PInfLayout.setHorizontalGroup(
            PInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PInfLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(PnlAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(PPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(PnlSig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        PInfLayout.setVerticalGroup(
            PInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PInfLayout.createSequentialGroup()
                .addGroup(PInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PInfLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(PnlAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PInfLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PInfLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(PnlSig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bg.add(PInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 680, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PnlSigMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_PnlSigMouseClicked
    {//GEN-HEADEREND:event_PnlSigMouseClicked
                cl.next(PPelicula);
    }//GEN-LAST:event_PnlSigMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnConsultaPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnConsultaPeliculas().setVisible(true);
            }
        });
    }
private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblFlecha;
    private javax.swing.JPanel PInf;
    private javax.swing.JPanel PPelicula;
    private javax.swing.JPanel PSup;
    private javax.swing.JPanel PnlAnt;
    private javax.swing.JPanel PnlSig;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel lblAnt;
    // End of variables declaration//GEN-END:variables
}
