/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Datos.*;
import control.Control;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import Datos.Conexion;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author santi
 */
public class VtnCompBol extends javax.swing.JFrame
{

    Control ctrl = new Control();
    ArrayList<Promociones> listarPromociones = new ArrayList<>();
    ArrayList<TipoBoleto> listarTipos = new ArrayList<>();

    /**
     * Creates new form VtnCompBol
     */
    public VtnCompBol()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblBoleto = new javax.swing.JLabel();
        lblIdPago = new javax.swing.JLabel();
        lblNoAs = new javax.swing.JLabel();
        lblPromocion = new javax.swing.JLabel();
        txtBoleto = new javax.swing.JTextField();
        txtIdPago = new javax.swing.JTextField();
        txtAsiento = new javax.swing.JTextField();
        lblSala = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnRegistrarCompra = new javax.swing.JButton();
        lblFuncion = new javax.swing.JLabel();
        txtIdFuncion = new javax.swing.JTextField();
        btnCancelarOp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblMetodo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        btnContinuaPago = new javax.swing.JButton();
        btnCancelarPago = new javax.swing.JButton();
        comboProm = new javax.swing.JComboBox<>();
        comboTipoBoleto = new javax.swing.JComboBox<>();
        comboMetodo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(26, 43, 76));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblBoleto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBoleto.setText("Numero de boleto:");

        lblIdPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdPago.setText("ID de pago:");

        lblNoAs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNoAs.setText("Numero de asiento:");

        lblPromocion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPromocion.setText("Clave de promocion:");

        txtIdPago.setEnabled(false);

        lblSala.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSala.setText("Tipo de boleto:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setText("Fecha de compra:");

        btnRegistrarCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarCompra.setText("Pagar");
        btnRegistrarCompra.setEnabled(false);
        btnRegistrarCompra.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarCompraActionPerformed(evt);
            }
        });

        lblFuncion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFuncion.setText("ID Funcion:");

        btnCancelarOp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarOp.setText("Cancelar");
        btnCancelarOp.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarOpActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("ID Cliente:");

        lblIdCliente.setEnabled(false);
        lblIdCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lblIdClienteActionPerformed(evt);
            }
        });

        lblMonto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMonto.setText("Monto a pagar:");

        txtMonto.setEnabled(false);

        lblMetodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMetodo.setText("Metodo de pago:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("DATOS DEL BOLETO");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("DATOS DE PAGO");

        btnContinuaPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnContinuaPago.setText("Confirmar");
        btnContinuaPago.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnContinuaPagoActionPerformed(evt);
            }
        });

        btnCancelarPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarPago.setText("Cancelar");
        btnCancelarPago.setEnabled(false);
        btnCancelarPago.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarPagoActionPerformed(evt);
            }
        });

        comboMetodo.setEnabled(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_cinetec1-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(comboProm, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBoleto)
                                    .addComponent(lblNoAs, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFecha))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtIdFuncion))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSala)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboTipoBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAsiento, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtBoleto)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnContinuaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarOp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdPago)
                                    .addComponent(lblMonto))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboMetodo, 0, 130, Short.MAX_VALUE)
                                    .addComponent(lblIdCliente)
                                    .addComponent(txtIdPago)
                                    .addComponent(txtMonto))))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMetodo)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(btnCancelarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(451, 451, 451))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lblIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncion))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdPago)
                            .addComponent(txtIdPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBoleto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoAs)
                            .addComponent(lblMonto)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPromocion))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMetodo)
                                    .addComponent(comboProm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSala)
                            .addComponent(comboTipoBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelarOp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnContinuaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarPagoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarPagoActionPerformed
    {//GEN-HEADEREND:event_btnCancelarPagoActionPerformed
        txtIdFuncion.setEnabled(true);
        txtBoleto.setEnabled(true);
        txtAsiento.setEnabled(true);
        comboProm.setEnabled(true);
        txtFecha.setEnabled(true);
        comboTipoBoleto.setEnabled(true);
        btnContinuaPago.setEnabled(true);
        btnCancelarOp.setEnabled(true);

        lblIdCliente.setEnabled(false);
        txtIdPago.setEnabled(false);
        comboMetodo.setEnabled(false);
        btnRegistrarCompra.setEnabled(false);
        btnCancelarPago.setEnabled(false);
    }//GEN-LAST:event_btnCancelarPagoActionPerformed

    private void btnContinuaPagoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContinuaPagoActionPerformed
    {//GEN-HEADEREND:event_btnContinuaPagoActionPerformed
        if ("".equals(txtIdFuncion.getText()) || "".equals(txtBoleto.getText()) || "".equals(txtAsiento.getText())
                || comboTipoBoleto.getSelectedIndex() == -1 || comboProm.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(null, "Espacios en blanco. Complete los campos obligatorios antes de continuar");
        } else
        {
            String cantidad = "";
            String promAplicada = comboProm.getSelectedItem().toString();
            String montoPorPagar = comboTipoBoleto.getSelectedItem().toString();
            switch (montoPorPagar)
            {
                case "NORMAL":
                {
                    if (promAplicada.equals("PROM-00000"))
                    {
                        cantidad = "80";
                    }
                    if (promAplicada.equals("PROM-00001"))
                    {
                        cantidad = "56";
                    }
                    if (promAplicada.equals("PROM-00002"))
                    {
                        cantidad = "40";
                    }
                    if (promAplicada.equals("PROM-00003"))
                    {
                        cantidad = "48";
                    }
                    break;
                }
                case "VIP":
                {
                    if (promAplicada.equals("PROM-00000"))
                    {
                        cantidad = "200";
                    }
                    if (promAplicada.equals("PROM-00001"))
                    {
                        cantidad = "140";
                    }
                    if (promAplicada.equals("PROM-00002"))
                    {
                        cantidad = "100";
                    }
                    if (promAplicada.equals("PROM-00003"))
                    {
                        cantidad = "120";
                    }
                    break;
                }
            }

            txtMonto.setText(cantidad);
            lblIdCliente.setEnabled(true);
            txtIdPago.setEnabled(true);
            comboMetodo.setEnabled(true);
            btnRegistrarCompra.setEnabled(true);
            btnCancelarPago.setEnabled(true);

            txtIdFuncion.setEnabled(false);
            txtBoleto.setEnabled(false);
            txtAsiento.setEnabled(false);
            comboProm.setEnabled(false);
            txtFecha.setEnabled(false);
            comboTipoBoleto.setEnabled(false);
            btnContinuaPago.setEnabled(false);
            btnCancelarOp.setEnabled(false);
        }


    }//GEN-LAST:event_btnContinuaPagoActionPerformed

    private void lblIdClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lblIdClienteActionPerformed
    {//GEN-HEADEREND:event_lblIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIdClienteActionPerformed

    private void btnCancelarOpActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarOpActionPerformed
    {//GEN-HEADEREND:event_btnCancelarOpActionPerformed
        if (txtIdFuncion.getText().equals("") && txtBoleto.getText().equals("")
                && txtAsiento.getText().equals("") && comboProm.getSelectedIndex() == -1 && txtFecha.getText().equals("")
                && comboTipoBoleto.getSelectedIndex() == -1 && lblIdCliente.getText().equals("") && txtIdPago.getText().equals("")
                && txtMonto.getText().equals("") && comboMetodo.getSelectedIndex() == -1)
        {
            this.dispose();
        } else
        {
            int confirma = JOptionPane.showConfirmDialog(null, "¿Desea descartar los cambios?", "CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION)
            {
                txtIdFuncion.setText("");
                txtBoleto.setText("");
                txtAsiento.setText("");
                comboProm.setSelectedIndex(-1);
                txtFecha.setText("");
                comboTipoBoleto.setSelectedIndex(-1);
                lblIdCliente.setText("");
                txtIdPago.setText("");
                txtMonto.setText("");
                comboMetodo.setSelectedIndex(-1);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnCancelarOpActionPerformed

    private void btnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarCompraActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarCompraActionPerformed
        try
        {
            double p = 0;
            String noBoleto = txtBoleto.getText();
            String idPago = txtIdPago.getText();
            String noAsiento = txtAsiento.getText();
            String cveProm = comboProm.getSelectedItem().toString();
            String tipoBoleto = comboTipoBoleto.getSelectedItem().toString();
            if (tipoBoleto.equals("NORMAL"))
            {
                p = 80;
            } else if (tipoBoleto.equals("VIP"))
            {
                p = 200;
            }
            if (comboTipoBoleto.getSelectedIndex() == -1)
            {
                tipoBoleto = "NORMAL";
            }
            String fechaComp = txtFecha.getText();
            String idFuncion = txtIdFuncion.getText();
            String idCliente = lblIdCliente.getText();
            String metodoPago = comboMetodo.getSelectedItem().toString();
            String montoPago = txtMonto.getText();

            double montoP = Double.parseDouble(montoPago);
            String idAsientoFuncion = idFuncion + "-" + noAsiento;

            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date fechaUtil = formato.parse(fechaComp);
            java.sql.Date fechaSQL = new java.sql.Date(fechaUtil.getTime());

            Connection conn = Conexion.getConnection();
            conn.setAutoCommit(false);

            try
            {
                Control ctr = new Control();
                boolean okPago = ctr.insertarP(conn, idPago, idCliente, metodoPago, montoP);
                boolean okBoleto, okModificacion;
                if (okPago)
                {
                    okBoleto = ctr.insertarB(conn, noBoleto, idPago, idAsientoFuncion, cveProm, tipoBoleto, fechaSQL, p);
                    if (okBoleto)
                    {
                        okModificacion = ctr.modificarEA(conn, idAsientoFuncion, "OCUPADO", noBoleto);
                        if (okModificacion)
                        {
                            JOptionPane.showMessageDialog(this, "Registro insertado con éxito.");
                            conn.commit();
                            
                            btnCancelarOp.setEnabled(true);
                            
                        } else
                        {
                            throw new SQLException();
                        }
                    } else
                    {
                        throw new SQLException();
                    }
                } else
                {
                    throw new SQLException();
                }
            } catch (SQLException e)
            {
                conn.rollback();
                System.out.println("java.sql.SQLIntegrityConstraintViolationException: " + e.getMessage());
            } finally
            {
                conn.setAutoCommit(true);
                conn.close();
            }

        } catch (SQLException ex)
        {
            System.out.println("java.sql.SQLIntegrityConstraintViolationException: " + ex.getMessage());
        } catch (ParseException ex)
        {
            Logger.getLogger(VtnCompBol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrarCompraActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        cargaComboPromociones();
        comboProm.setSelectedIndex(-1);
        cargaComboTipoBoleto();
        comboTipoBoleto.setSelectedIndex(-1);
        cargaMetodosPago();
        comboMetodo.setSelectedIndex(-1);
    }//GEN-LAST:event_formWindowOpened

    public void cargaComboPromociones()
    {
        listarPromociones = ctrl.leerTodasPromociones();

        for (Promociones prom : listarPromociones)
        {
            comboProm.addItem(prom.getCvePromocion());
        }
    }

    public void cargaComboTipoBoleto()
    {
        listarTipos = ctrl.leerTodosTipoBoleto();

        for (TipoBoleto tb : listarTipos)
        {
            comboTipoBoleto.addItem(tb.getTipoBoleto());
        }
    }

    public void cargaMetodosPago()
    {
        comboMetodo.addItem("CREDITO");
        comboMetodo.addItem("DEBITO");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnCompBol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnCompBol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnCompBol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnCompBol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnCompBol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarOp;
    private javax.swing.JButton btnCancelarPago;
    private javax.swing.JButton btnContinuaPago;
    private javax.swing.JButton btnRegistrarCompra;
    private javax.swing.JComboBox<String> comboMetodo;
    private javax.swing.JComboBox<String> comboProm;
    private javax.swing.JComboBox<String> comboTipoBoleto;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblBoleto;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JTextField lblIdCliente;
    private javax.swing.JLabel lblIdPago;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNoAs;
    private javax.swing.JLabel lblPromocion;
    private javax.swing.JLabel lblSala;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtBoleto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdFuncion;
    private javax.swing.JTextField txtIdPago;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
