/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import Datos.*;
import control.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jrme0
 */
public class VtnPrincipal extends javax.swing.JFrame
{

    DefaultTableModel model;
    ArrayList<Cines> listarCines = new ArrayList<>();
    Conexion conn = new Conexion();
    boolean isConnected = conn.conectar();
    Control ctrl = new Control();

    /**
     * Creates new form Principal
     */
    public VtnPrincipal()
    {
        super("PROYECTO FBD - UNIDADES 5 y 6");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlPrincipal = new javax.swing.JPanel();
        barraLateral = new javax.swing.JPanel();
        btnRegistrarCliente = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        btnComprar = new javax.swing.JPanel();
        lblComprar = new javax.swing.JLabel();
        btnRegistrarPelicula = new javax.swing.JPanel();
        lblRegistroPelicula = new javax.swing.JLabel();
        btnCartelera = new javax.swing.JPanel();
        lblCartelera = new javax.swing.JLabel();
        pnlBarraTitulo = new javax.swing.JPanel();
        lblOperaciones = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblListaSucursales = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCines = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        pnlPrincipal.setBackground(new java.awt.Color(226, 232, 243));

        barraLateral.setBackground(new java.awt.Color(136, 167, 208));

        btnRegistrarCliente.setBackground(new java.awt.Color(136, 167, 208));
        btnRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnRegistrarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnRegistrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnRegistrarClienteMouseExited(evt);
            }
        });

        lblRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setText("REGISTRAR CLIENTE");

        javax.swing.GroupLayout btnRegistrarClienteLayout = new javax.swing.GroupLayout(btnRegistrarCliente);
        btnRegistrarCliente.setLayout(btnRegistrarClienteLayout);
        btnRegistrarClienteLayout.setHorizontalGroup(
            btnRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarClienteLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnRegistrarClienteLayout.setVerticalGroup(
            btnRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarClienteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnComprar.setBackground(new java.awt.Color(136, 167, 208));
        btnComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnComprarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnComprarMouseExited(evt);
            }
        });

        lblComprar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblComprar.setForeground(new java.awt.Color(255, 255, 255));
        lblComprar.setText("COMPRAR BOLETO");

        javax.swing.GroupLayout btnComprarLayout = new javax.swing.GroupLayout(btnComprar);
        btnComprar.setLayout(btnComprarLayout);
        btnComprarLayout.setHorizontalGroup(
            btnComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnComprarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblComprar)
                .addGap(55, 55, 55))
        );
        btnComprarLayout.setVerticalGroup(
            btnComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComprarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnRegistrarPelicula.setBackground(new java.awt.Color(136, 167, 208));
        btnRegistrarPelicula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarPelicula.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnRegistrarPeliculaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnRegistrarPeliculaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnRegistrarPeliculaMouseExited(evt);
            }
        });

        lblRegistroPelicula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRegistroPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistroPelicula.setText("REGISTRAR PELÍCULA");

        javax.swing.GroupLayout btnRegistrarPeliculaLayout = new javax.swing.GroupLayout(btnRegistrarPelicula);
        btnRegistrarPelicula.setLayout(btnRegistrarPeliculaLayout);
        btnRegistrarPeliculaLayout.setHorizontalGroup(
            btnRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRegistrarPeliculaLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblRegistroPelicula)
                .addGap(41, 41, 41))
        );
        btnRegistrarPeliculaLayout.setVerticalGroup(
            btnRegistrarPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegistrarPeliculaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblRegistroPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnCartelera.setBackground(new java.awt.Color(136, 167, 208));
        btnCartelera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCartelera.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCarteleraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnCarteleraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnCarteleraMouseExited(evt);
            }
        });

        lblCartelera.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCartelera.setForeground(new java.awt.Color(255, 255, 255));
        lblCartelera.setText("VER CARTELERA");

        javax.swing.GroupLayout btnCarteleraLayout = new javax.swing.GroupLayout(btnCartelera);
        btnCartelera.setLayout(btnCarteleraLayout);
        btnCarteleraLayout.setHorizontalGroup(
            btnCarteleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCarteleraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCartelera)
                .addGap(68, 68, 68))
        );
        btnCarteleraLayout.setVerticalGroup(
            btnCarteleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCarteleraLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlBarraTitulo.setBackground(new java.awt.Color(72, 111, 153));

        lblOperaciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblOperaciones.setText("OPERACIONES");

        javax.swing.GroupLayout pnlBarraTituloLayout = new javax.swing.GroupLayout(pnlBarraTitulo);
        pnlBarraTitulo.setLayout(pnlBarraTituloLayout);
        pnlBarraTituloLayout.setHorizontalGroup(
            pnlBarraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraTituloLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(lblOperaciones)
                .addGap(82, 82, 82))
        );
        pnlBarraTituloLayout.setVerticalGroup(
            pnlBarraTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraTituloLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout barraLateralLayout = new javax.swing.GroupLayout(barraLateral);
        barraLateral.setLayout(barraLateralLayout);
        barraLateralLayout.setHorizontalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btnComprar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarPelicula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCartelera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlBarraTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        barraLateralLayout.setVerticalGroup(
            barraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralLayout.createSequentialGroup()
                .addComponent(pnlBarraTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCartelera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTitulo.setBackground(new java.awt.Color(83, 121, 164));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CINE-TEC - MENÚ PRINCIPAL");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblTitulo)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        lblListaSucursales.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblListaSucursales.setText("SUCURSALES DISPONIBLES");

        tblCines.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tblCines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "ID CINE", "NOMBRE CINE"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblCines.setRowHeight(35);
        tblCines.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tblCines);
        if (tblCines.getColumnModel().getColumnCount() > 0)
        {
            tblCines.getColumnModel().getColumn(0).setResizable(false);
            tblCines.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblListaSucursales)
                        .addGap(74, 74, 74))))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblListaSucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(barraLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        conn.desconectar();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    
    
    private void btnComprarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnComprarMouseExited
    {//GEN-HEADEREND:event_btnComprarMouseExited
        btnComprar.setBackground(new Color(136, 167, 208));
    }//GEN-LAST:event_btnComprarMouseExited

    private void btnComprarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnComprarMouseEntered
    {//GEN-HEADEREND:event_btnComprarMouseEntered
        btnComprar.setBackground(new Color(104, 141, 185));
    }//GEN-LAST:event_btnComprarMouseEntered

    private void btnComprarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnComprarMouseClicked
    {//GEN-HEADEREND:event_btnComprarMouseClicked

    }//GEN-LAST:event_btnComprarMouseClicked
    
    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        if (!isConnected)
        {
            JOptionPane.showMessageDialog(null, "No es posible acceder en este momento. Intente de nuevo mas tarde.", "Error de conexion", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        } else
        {
            listarCines();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnRegistrarPeliculaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarPeliculaMouseClicked
    {//GEN-HEADEREND:event_btnRegistrarPeliculaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPeliculaMouseClicked

    private void btnRegistrarPeliculaMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarPeliculaMouseEntered
    {//GEN-HEADEREND:event_btnRegistrarPeliculaMouseEntered
        btnRegistrarPelicula.setBackground(new Color(104, 141, 185));
    }//GEN-LAST:event_btnRegistrarPeliculaMouseEntered

    private void btnRegistrarPeliculaMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarPeliculaMouseExited
    {//GEN-HEADEREND:event_btnRegistrarPeliculaMouseExited
        btnRegistrarPelicula.setBackground(new Color(136, 167, 208));
    }//GEN-LAST:event_btnRegistrarPeliculaMouseExited
    
    
    VtnClientes regClientes = new VtnClientes();
    private void btnRegistrarClienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarClienteMouseClicked
    {//GEN-HEADEREND:event_btnRegistrarClienteMouseClicked
        regClientes.setVisible(true);
    }//GEN-LAST:event_btnRegistrarClienteMouseClicked

    private void btnRegistrarClienteMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarClienteMouseEntered
    {//GEN-HEADEREND:event_btnRegistrarClienteMouseEntered
        btnRegistrarCliente.setBackground(new Color(104, 141, 185));
    }//GEN-LAST:event_btnRegistrarClienteMouseEntered

    private void btnRegistrarClienteMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarClienteMouseExited
    {//GEN-HEADEREND:event_btnRegistrarClienteMouseExited
        btnRegistrarCliente.setBackground(new Color(136, 167, 208));
    }//GEN-LAST:event_btnRegistrarClienteMouseExited

    
    
    private void btnCarteleraMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCarteleraMouseClicked
    {//GEN-HEADEREND:event_btnCarteleraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarteleraMouseClicked

    private void btnCarteleraMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCarteleraMouseEntered
    {//GEN-HEADEREND:event_btnCarteleraMouseEntered
        btnCartelera.setBackground(new Color(104, 141, 185));
    }//GEN-LAST:event_btnCarteleraMouseEntered

    private void btnCarteleraMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCarteleraMouseExited
    {//GEN-HEADEREND:event_btnCarteleraMouseExited
        btnCartelera.setBackground(new Color(136, 167, 208));
    }//GEN-LAST:event_btnCarteleraMouseExited
    
    public void listarCines()
    {
        model = (DefaultTableModel) tblCines.getModel();
        Object obj[] = new Object[8];
        model.setRowCount(0);
        listarCines = ctrl.leerTodosCines();
        for (Cines cn : listarCines)
        {
            obj[0] = cn.getIdCine();
            obj[1] = cn.getNombreCine();
            model.addRow(obj);
        }
        tblCines.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraLateral;
    private javax.swing.JPanel btnCartelera;
    private javax.swing.JPanel btnComprar;
    private javax.swing.JPanel btnRegistrarCliente;
    private javax.swing.JPanel btnRegistrarPelicula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCartelera;
    private javax.swing.JLabel lblComprar;
    private javax.swing.JLabel lblListaSucursales;
    private javax.swing.JLabel lblOperaciones;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblRegistroPelicula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBarraTitulo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblCines;
    // End of variables declaration//GEN-END:variables
}
