/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;


import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;

/**
 *
 * @author trist
 */
public class VtnRegisC extends javax.swing.JFrame
{
    private HashMap<String, String> cineIDMap; // Mapa para almacenar el ID del cine


    /**
     * Creates new form VtnRegisC
     */
    public VtnRegisC()
    {
        initComponents();
        customInitComponents(); // <-- Esta línea es nueva
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnSeleccionar.setText("Confirma seleccion");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(btnSeleccionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionar)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSeleccionarActionPerformed
    {//GEN-HEADEREND:event_btnSeleccionarActionPerformed
 if (!jList1.isSelectionEmpty()) {
        // Obtener el nombre del cine seleccionado
        String cineSeleccionado = jList1.getSelectedValue();
        
        // Obtener el ID del HashMap
        String idCine = cineIDMap.get(cineSeleccionado);

        // Verificar en consola si se pasa correctamente
        System.out.println("ID del cine seleccionado: " + idCine);

        // ==========================
        // Validación del ID del cine
        // ==========================
        if (idCine == null || idCine.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: No se pudo recuperar el ID del cine seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método para evitar errores
        }

        // Pregunta de confirmación
        int confirm = JOptionPane.showConfirmDialog(this, "¿Deseas registrar un cliente para el cine: " + cineSeleccionado + "?", "Confirmar Selección", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Aquí debería pasar correctamente el valor al constructor
            VtnRegisFinal ventanaRegistro = new VtnRegisFinal(idCine); // ✅ Constructor correcto
            ventanaRegistro.setVisible(true);
            this.dispose(); // Cerrar la ventana actual
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un cine.", "Selección requerida", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnSeleccionarActionPerformed
    
    

    
private void customInitComponents() {
    // Inicialización del modelo de lista
    DefaultListModel<String> modeloLista = new DefaultListModel<>();
    jList1.setModel(modeloLista);

    // Inicialización del HashMap
    cineIDMap = new HashMap<>();  

    // ==========================
    // Cargar datos desde la Base de Datos
    // ==========================
    String url = "jdbc:oracle:thin:@//25.50.80.247:1521/xepdb1";
    String usuario = "equipoFBD";
    String password = "10714223";

    try (Connection conn = DriverManager.getConnection(url, usuario, password)) {
        System.out.println("Conexión exitosa a Oracle");

        // Consulta para traer los datos
        String query = "SELECT ID_CINE, NOMBRE_CINE FROM CINES";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        // Agregar cada cine al modelo de la lista y al HashMap
        while (rs.next()) {
            String idCine = rs.getString("ID_CINE");
            String nombreCine = rs.getString("NOMBRE_CINE");

            modeloLista.addElement(nombreCine);      // Agregar al JList
            cineIDMap.put(nombreCine, idCine);       // Guardar en el HashMap
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + ex.getMessage());
    }
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegisC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegisC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegisC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegisC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegisC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
